### ISSUE TITLE
Create Project Content Type

### ISSUE THREAD

**Issue by colinsf** [CodeForTucson/codefortucson-site#20]
#19 made me realize that we should find a way to standardize the way that projects are entered and rendered by the site.  This will prevent our **Stuff we've made** section from turning into the Wild West and looking like a hackerspace WordPress blog.

A Project should have some information that is required like a name and a description, and some information that is optional like the project owner, media like presentations or PDFs, and hopefully a link to the repository.

    Project
    ├── required
    │   ├── description
    │   └── name
    └── optional
        ├── contact
        ├── media
        └── source code

I am not familiar enough with Jekyll to say whether custom content types are possible or easy enough to build, but I am confident that with a couple of quick Googles I can get enough information to close this issue one way or another.

**Comment by dmsnell** [comment]
This issue was moved to CodeForTucson/codefortucson.org#7
