### ISSUE TITLE
Fix relative/absolute URLs

### ISSUE THREAD

**Issue by meiqimichelle** [CodeForTucson/codefortucson-site#25]
- `baseurl` == `url` in `config` at the moment
- this should probably be relative links, but I couldn't figure out how to make this work with gh-pages and DNS settings

**Comment by dmsnell** [comment]
This issue was moved to CodeForTucson/codefortucson.org#5

**Comment by dmsnell** [comment]
#38 should take care of this.

Jekyll won't let us include template variables in the SASS directory, but by moving the definitions of `$site-baseurl` into `style.css` before `@import "custom"`, we are able to set it equal to the Jekyll variable:

```scss
$site-baseurl: {{ site.baseurl }};

@import "custom"
```

Now that variable is dependent on the config variable set at build-time and will be correct for local and production environments.

**Comment by dmsnell** [comment]
Fixed in #38
