### ISSUE TITLE
Set up google analytics and add to config

### ISSUE THREAD

**Issue by meiqimichelle** [CodeForTucson/codefortucson-site#3]

**Comment by dmsnell** [comment]
This issue was moved to CodeForTucson/codefortucson.org#9

**Comment by dtwen** [comment]
I would suggest using GTM (https://www.google.com/analytics/tag-manager/) to implement GA on the site as it's more flexible and you can track specific events i.e. click events on buttons.

**Comment by meiqimichelle** [comment]
Interesting! I've never used that service before, thank you for the tip @dtwen! :confetti_ball:  I'll look into it for this (and some of my other projects, mwhahah).
