### ISSUE TITLE
Potential bug on collapsed nav

### ISSUE THREAD

**Issue by meiqimichelle** [CodeForTucson/codefortucson-site#48]
When I click on the hamburger nav after it is hamburger'd, nothing happens. The nav menu should drop down. HOWEVER....dot dot dot...I'm on a plane right now with very slow internet so I'd love for someone else to confirm or (hopefully) disprove. I tested on Firefox at the smallest screen width I can pull to.

**Comment by dmsnell** [comment]
> after it is hamburger'd

loving the verbiage
