### ISSUE TITLE
Investigate previewing changes with Jekit

### ISSUE THREAD

**Issue by dmsnell** [CodeForTucson/codefortucson-site#62]
Found on the [Code for America repo](https://github.com/codeforamerica/codeforamerica.org)

https://jekit.codeforamerica.org

**Comment by dmsnell** [comment]
This is trivially easy:

http://jekit.codeforamerica.org/codefortucson/codefortucson-site/

See [this page](https://jekit.codeforamerica.org) for information on how to preview a specific branch or GitHub reference ID.

**Comment by dmsnell** [comment]
Jekit does not to appear to have been under active development for about a year and a half. There are strange issues I'm seeing with some assets loading from `codefortucson.org` while others are (not) loading from `codefortucson.github.io/codefortucson-site/`. I'm not sure after all if this is a good tool for us to use.

I have filed an [issue](https://github.com/codeforamerica/git-jekyll-preview/issues/16) with the project and we will see what the response will be like, if any.

**Comment by meiqimichelle** [comment]
Seems like this is a non-starter for now :-/ @dmsnell I suggest closing this issue, unless you'd like to keep it open in case Jekit comes under active development again. What are your thoughts?

**Comment by dmsnell** [comment]
@meiqimichelle agreed. I did get a response from @migurski on that issue but the situation doesn't look too good. it's a pretty complicated script that runs and I'm not sure I can dedicate any energy on it to fix some of the glitches.
